meta:
  version: 0.3.1
  name: korne
  author: XuyuanPang

units:
  kx: cx
  ky: cy

  pd: 2
  px: kx + pd
  py: ky + pd

  mcu_width: 17.78
  mcu_height: 33
  mcu_shift_y: 12

  m2r: 1.05 # radius of m2 screw
  screw_hole_size: m2r # screw hole size

points:
  key:
    width: kx
    height: ky
    bind: 0
  zones:
    matrix:
      key:
        padding: ky
        spread: u
      columns:
        pinky:
          key:
            bind: [0, 0.5 pd, 0, 0]
          rows:
            top.kn: '0'
            home.kn: 1
            bottom.kn: 2
            bottom.bind: 0
        ring:
          key:
            stagger: 0.65 ky
            bind: [0, 0.5 pd, 0, 0]
          rows:
            top.kn: 3
            home.kn: 4
            bottom.kn: 5
            bottom.bind: [0, 0, 0, 0.5 pd]
        middle:
          key.stagger: 0.25 ky
          rows:
            top.kn: 6
            home.kn: 7
            bottom.kn: 8
            bottom.bind: [0.5 pd, 0]
        index:
          key:
            stagger: -0.35 ky
            bind: [0, 0, 0, 0.5 pd]
          rows:
            top.kn: 9
            home.kn: 10
            bottom.kn: 11
        inner:
          key:
            stagger: -0.2 ky
            bind: [0, 0, 0, 0.5 pd]
          rows:
            top.kn: 12
            home.kn: 13
            bottom.kn: 14
            bottom.bind: [0, 0, ky, 0.5 pd]
      rows:
        bottom:
        home:
        top:

    thumbfan:
      anchor:
        - ref: matrix_middle_bottom
          shift: [0.8 kx + 1, -1.7 ky]
      key:
        spread: kx
        splay: -15
      columns:
        near.key:
          splay: 0
          kn: 15
          bind: [2 ky, kx, 0, 0]
        home.key:
          kn: 16
          bind: [pd, 0]
          origin: [-0.5 kx, -0.5 ky]
        far.key:
          kn: 17
          bind: [0, 0, 0, 2 kx]
          origin: [-0.5 kx, -0.5 ky]
      rows:
        thumb:

    # helpers to draw mcu area
    _helper_mcu_topleft:
      anchor:
        - ref: matrix_inner_top
          shift: [0.5 kx, 0.5 ky - mcu_shift_y]
    _helper_mcu_topright:
      anchor:
        - ref: _helper_mcu_topleft
          shift: [mcu_width + 3, 0]
    _helper_mcu_bottomleft:
      anchor:
        - aggregate:
            method: intersect
            parts:
              - ref: thumbfan_far_thumb
                shift: [0, 0.5 ky]
                rotate: 90
              - ref: matrix_inner_bottom
                shift: [0.5 kx, 0]
    _helper_mcu_bottommiddle:
      anchor:
        - ref: thumbfan_far_thumb
          shift: [0.5 kx, 0.5 ky]
    _helper_mcu_bottomright:
      anchor:
        - aggregate:
            method: intersect
            parts:
              - _helper_mcu_bottommiddle
              - _helper_mcu_topright

    _helper_mcu_topmiddle:
      anchor:
        - aggregate.parts:
            - ref: _helper_mcu_topleft
            - ref: _helper_mcu_topright

    _helper_mcu_center:
      anchor:
        - ref: _helper_mcu_topmiddle
          shift: [0, -0.5 mcu_height - 3]

    _helper_mcu_cover_holes_left:
      anchor:
        - ref: _helper_mcu_bottomleft
          orient: -60
          shift: [0, 3*1.1547]

    _helper_mcu_cover_holes_right:
      anchor:
        - ref: _helper_mcu_bottomright
          orient: 75
          shift: [0, 3*1.035]

    _helper_pcb_power:
      anchor:
        - ref: _helper_mcu_topright
          shift: [-1.75, -mcu_height - 10]

    _helper_pcb_jstph:
      anchor:
        - ref: thumbfan_far_thumb
          shift: [-1, 0.5 ky + 5]
          rotate: -120

    _helper_pcb_reset:
      anchor:
        - ref: _helper_mcu_topmiddle
          shift: [0, -1.7]
          rotate: 90

outlines:
  raw:
    - what: rectangle
      where:
        - -/_helper_.*/
      asym: source
      size: [kx + 2, ky + 2]
      corner: pd
  switches:
    - what: rectangle
      where:
        - -/_helper_.*/
      size: 14
  switches_outer:
    - what: rectangle
      where:
        - -/_helper_.*/
      size: 15

  keywell:
    - what: rectangle
      where:
        - /^matrix_.*/
        - /^thumbfan_.*/
      size: [kx, ky]
      bound: true

  mcu_area:
    - what: polygon
      points:
        - _helper_mcu_topleft
        - _helper_mcu_bottomleft
        - _helper_mcu_bottommiddle
        - _helper_mcu_bottomright
        - _helper_mcu_topright

  _board:
    - keywell
    - mcu_area

  board:
    - name: _board
      fillet: 1.5

  mcu_cover_holes:
    - what: circle
      where:
        - /_helper_mcu_cover_holes_.*/
      radius: screw_hole_size

  _mcu_cover:
    - mcu_area
  mcu_cover:
    - name: _mcu_cover
      expand: -0.5
    - -mcu_cover_holes

  _preview_keycaps:
    - what: rectangle
      where:
        - /^matrix_.*/
        - /^thumbfan_.*/
      size: [kx - 0.5, ky - 0.5]
      bound: false
      corner: 1.5

  _preview_mcu:
    - what: rectangle
      where: _helper_mcu_center
      size: [mcu_width, mcu_height]

  _preview_battery:
    - what: rectangle
      where:
        - ref: _helper_mcu_center
      size: [12, 30]

  preview:
    - board
    - -_preview_keycaps
    - ^mcu_cover
    - ^_preview_mcu
    - ^_preview_battery
    - ^switches

pcbs:
  board:
    template: kicad8
    outlines:
      main:
        outline: board
      keycaps:
        outline: _preview_keycaps
        layer: Dwgs.User
      mcu:
        outline: mcu_area
        layer: Dwgs.User
    footprints:
      choc_switches:
        what: infused-kim/choc
        where:
          - /^matrix_.*/
          - /^thumbfan_.*/
        params:
          show_keycaps: false
          reverse: true
          hotswap: false
          solder: true
          from: "GND"
          to: "k{{kn}}"

      mcu:
        what: infused-kim/nice_nano_pretty
        where:
          ref:
            - _helper_mcu_center
        params:
          # top row
          P1: k12
          P0: k9
          P2: k6
          P3: k3
          P4: k0

          # home row
          P5: k13
          P6: k10
          P7: k7
          P8: k4
          P9: k1

          # bottom row
          P21: k14
          P20: k11
          P19: k8
          P18: k5
          P15: k2

          # thumb fan
          P14: k15
          P16: k16
          P10: k17

          # P0_label: k0
          # P1_label: k1
          # P2_label: k2
          # P3_label: k3
          # P4_label: k4
          # P5_label: k5
          # P6_label: k6
          # P7_label: k7
          # P8_label: k8
          # P9_label: k9
          # P10_label: k10
          # P14_label: k11
          # P15_label: k12
          # P16_label: k13
          # P18_label: k14
          # P19_label: k15
          # P20_label: k16
          # P21_label: k17

      reset:
        what: infused-kim/switch_reset
        where:
          ref:
            - _helper_pcb_reset
        params:
          reverse: true
          from: RST
          to: GND
      reset_via_rst:
        what: via
        where:
          ref:
            - _helper_pcb_reset
          shift: [-0.71, 0]
        params:
          net: "RST"

      power:
        what: infused-kim/switch_power
        where:
          ref:
            - _helper_pcb_power
        params:
          reverse: true
          from: BAT+
          to: RAW
      power_on_r:
        what: infused-kim/text
        where:
          ref:
            - _helper_pcb_power
          shift: [0, 5.2]
        params:
          reverse: true
          text: "ON"
      power_off_r:
        what: infused-kim/text
        where:
          ref:
            - _helper_pcb_power
          shift: [0, -5.2]
        params:
          reverse: true
          text: "OFF"

      jstph:
        what: jstph
        where:
          ref:
            - _helper_pcb_jstph
        params:
          neg: "GND"
          pos: "BAT+"
      icon_bat_l:
        what: infused-kim/icon_bat
        where:
          ref:
            - _helper_pcb_jstph
          shift: [0, 2]
      icon_bat_r:
        what: infused-kim/icon_bat
        where:
          ref:
            - _helper_pcb_jstph
          shift: [0, 2]
        params:
          side: "B"

      mcu_cover_holes:
        what: infused-kim/mounting_hole
        where:
          - /_helper_mcu_cover_holes_.*/
        params:
          outline: 0.5

      jlc_marker:
        what: text
        where:
          - aggregate.parts:
              - ref: matrix_index_bottom
              - ref: thumbfan_near_thumb
            affect: "y"
          - ref: thumbfan_near_thumb
            shift: [0.5 kx, 0]
            affect: "x"
        params:
          text: "JLCJLCJLCJLC"
