units:
  kx: cx
  ky: cy
  pd: 2

  px: kx + pd
  py: ky + pd
points:
  key:
    footprints:
      choc_hotswap:
        type: choc
        params:
          hotswap: true
          reverse: true
          keycaps: true
        nets:
          from: =colrow
          to: =column_net
      diode:
        type: diode
        nets:
          from: =colrow
          to: =row_net
        anchor:
          shift: [0, -5]
  zones:
    matrix:
      key:
        padding: ky
        spread: kx
      columns:
        pinky:
          key.column_net: col_pinky
        ring:
          key.stagger: 0.5 ky
          key.column_net: col_ring
        middle:
          key.stagger: 0.2 ky
          key.column_net: col_middle
        index:
          key.stagger: -0.2 ky
          key.column_net: col_index
        inner:
          key.stagger: -0.1 ky
          key.column_net: col_inner
      rows:
        bottom:
          row_net: row_bottom
        home:
          row_net: row_home
        top:
          row_net: row_top
    thumbfan:
      anchor:
        ref: matrix_middle_bottom
        shift: [0.5 kx, -1.4 ky]
      key:
        padding: ky
        spread: kx
      columns:
        near:
          key.column_net: col_middle
        home:
          key:
            splay: -15
            origin: [-0.5 kx, -1 ky]
            column_net: col_index
        far:
          key:
            splay: -15
            origin: [-0.5 kx, -1 ky]
            rotate: 90
            width: 1.5 kx
            shift: [0, 0.25 kx]
            column_net: col_inner
      rows:
        thumb:
          row_net: row_thumb
outlines:
  raw:
    - what: rectangle
      where: true
      asym: source
      size: [kx + 2, ky + 2]
      corner: pd
  keys:
    - what: rectangle
      where: true
      size: [kx - 0.5, ky - 0.5]
      bound: false
  board:
    - what: polygon
      operation: stack
      fillet: 1
      points:
        - ref: matrix_pinky_top
          shift: [-0.5 px, 0.5 py]
        - ref: matrix_pinky_top
          shift: [0.5 px - pd, 0.5 py]

        - ref: matrix_ring_top
          shift: [-0.5 px, 0.5 py]
        - ref: matrix_ring_top
          shift: [0.5 px - pd, 0.5 py]

        - ref: matrix_middle_top
          shift: [-0.5 px, 0.5 py]
        - ref: matrix_middle_top
          shift: [0.5 px, 0.5 py]

        - ref: matrix_index_top
          shift: [-0.5 px + pd, 0.5 py]
        - ref: matrix_index_top
          shift: [0.5 px, 0.5 py]

        - ref: matrix_inner_top
          shift: [-0.5 px + pd, 0.5 py]
        - ref: matrix_inner_top
          shift: [0.5 px, 0.5 py]

        - ref: matrix_inner_top
          shift: [0.5 px + 23.65, 0.5 py]

        - ref: thumbfan_far_thumb
          shift: [0.75 px, -0.5 py]
        - ref: thumbfan_far_thumb
          shift: [-0.75 px, -0.5 py]

        - ref: thumbfan_home_thumb
          shift: [0.5 px, -0.5 py]

        - ref: thumbfan_near_thumb
          shift: [-0.5 px, -0.5 py]

        - ref: matrix_pinky_bottom
          shift: [1 px, -0.5 py]

        - ref: matrix_pinky_bottom
          shift: [0.5 px, -0.5 py]

        - ref: matrix_pinky_bottom
          shift: [-0.5 px, -0.5 py]
  combo:
    - name: board
    - name: keys
      operation: subtract
pcbs:
  mycorne:
    outlines:
      main:
        outline: board
    footprints:
      choc_hotswap:
        what: choc
        where:
        - /matrix_.*/
        - /thumbfan_.*/
        params:
          keycaps: true
          reverse: true
          hotswap: true
          from: "{{colrow}}"
          to: "{{column_net}}"
      diode:
        what: diode
        where:
        - /matrix_.*/
        - /thumbfan_.*/
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [0, -5]
      mcu_left:
        what: promicro
        where:
          ref:
          - matrix_inner_top
          shift: [20, -11]
          rotate: 270
        params:
          orientation: down
          P4: row_top
          P5: row_home
          P6: row_bottom
          P7: row_thumb
          P14: col_inner
          P15: col_index
          P18: col_middle
          P19: col_ring
          P20: col_pinky
      mcu_right:
        what: promicro
        where:
          ref:
          - matrix_inner_top
          shift: [22.5, -12.25]
          rotate: 270
        params:
          orientation: up
