units:
  kx: cx
  ky: cy
  pd: 2

  px: kx + pd
  py: ky + pd
points:
  zones:
    matrix:
      key:
        padding: ky
        spread: kx
      columns:
        pinky:
        ring:
          key.stagger: 0.5 ky
        middle:
          key.stagger: 0.2 ky
        index:
          key.stagger: -0.2 ky
        inner:
          key.stagger: -0.1 ky
      rows:
        bottom:
        home:
        top:
    thumbfan:
      anchor:
        ref: matrix_middle_bottom
        shift: [0.5 kx, -1.5 ky]
      key:
        padding: ky
        spread: kx
      columns:
        near:
        home:
          key:
            splay: -15
            origin: [-0.5 kx, -1 ky]
        far:
          key:
            splay: -15
            origin: [-0.5 kx, -1 ky]
            rotate: 90
            width: 1.5 kx
            shift: [0, 0.25 kx]
      rows:
        thumb:
outlines:
  raw:
    - what: rectangle
      where: true
      asym: source
      size: [kx + 2, ky + 2]
      corner: pd
  keys:
    - what: rectangle
      where: true
      size: [kx - 0.5, ky - 0.5]
      bound: false
  board:
    - what: polygon
      operation: stack
      fillet: 1
      points:
        - ref: matrix_pinky_top
          shift: [-0.5 px, 0.5 py]
        - ref: matrix_pinky_top
          shift: [0.5 px - pd, 0.5 py]

        - ref: matrix_ring_top
          shift: [-0.5 px, 0.5 py]
        - ref: matrix_ring_top
          shift: [0.5 px - pd, 0.5 py]

        - ref: matrix_middle_top
          shift: [-0.5 px, 0.5 py]
        - ref: matrix_middle_top
          shift: [0.5 px, 0.5 py]

        - ref: matrix_index_top
          shift: [-0.5 px + pd, 0.5 py]
        - ref: matrix_index_top
          shift: [0.5 px, 0.5 py]

        - ref: matrix_inner_top
          shift: [-0.5 px + pd, 0.5 py]
        - ref: matrix_inner_top
          shift: [0.5 px, 0.5 py]

        - ref: matrix_inner_bottom
          shift: [0.5 px, -0.5 py + 3.5]

        - ref: thumbfan_far_thumb
          shift: [0.75 px, 0.5 py]
        - ref: thumbfan_far_thumb
          shift: [0.75 px, -0.5 py]
        - ref: thumbfan_far_thumb
          shift: [-0.75 px, -0.5 py]

        - ref: thumbfan_home_thumb
          shift: [0.5 px, -0.5 py]

        - ref: thumbfan_near_thumb
          shift: [-0.5 px, -0.5 py]

        - ref: matrix_pinky_bottom
          shift: [1 px, -0.5 py]

        - ref: matrix_pinky_bottom
          shift: [0.5 px, -0.5 py]

        - ref: matrix_pinky_bottom
          shift: [-0.5 px, -0.5 py]
  combo:
    - name: board
    - name: keys
      operation: subtract
