meta:
  version: 0.3.1
  name: korne
  author: XuyuanPang

units:
  kx: cx
  ky: cy

  pd: 2
  px: kx + pd
  py: ky + pd

  thumb_shift: 1.6 ky

  mcu_width: 17.78
  mcu_height: 33

  m2r: 1.05 # radius of m2 screw
  screw_hole_size: m2r # screw hole size

points:
  key:
    width: kx
    height: ky
    bind: 0
  zones:
    matrix:
      key:
        padding: ky
        spread: u
      columns:
        pinky:
          key:
            bind: [0, 0.5 pd, 0, 0]
          rows:
            top.kn: '0'
            home.kn: 1
            bottom.kn: 2
            bottom.bind: 0
        ring:
          key:
            stagger: 0.65 ky
            bind: [0, 0.5 pd, 0, 0]
          rows:
            top.kn: 3
            home.kn: 4
            bottom.kn: 5
            bottom.bind: [0, 0, 0, 0.5 pd]
        middle:
          key.stagger: 0.25 ky
          rows:
            top.kn: 6
            home.kn: 7
            bottom.kn: 8
            bottom.bind: [0.5 pd, 0]
        index:
          key:
            stagger: -0.35 ky
            bind: [0, 0, 0, 0.5 pd]
          rows:
            top.kn: 9
            home.kn: 10
            bottom.kn: 11
        inner:
          key:
            stagger: -0.2 ky
            bind: [0, 0, 0, 0.5 pd]
          rows:
            top.kn: 12
            home.kn: 13
            bottom.kn: 14
      rows:
        bottom:
        home:
        top:

    thumbfan:
      anchor:
        - ref: matrix_middle_bottom
          shift: [0.8 kx, -1.8 ky]
      key:
        spread: kx
        splay: -15
        bind: [0, 0]
      columns:
        near.key:
          splay: 0
          kn: 15
        home.key:
          origin: [-0.5 kx, -0.5 ky]
          kn: 16
          bind: [pd, 0]
        far.key:
          origin: [-0.5 kx, -0.5 ky]
          kn: 17
      rows:
        thumb:

    _helper_topright:
      anchor:
        - ref: matrix_inner_top
          shift: [0, 0.5 ky]
          affect: "y"
        - ref: thumbfan_far_thumb
          shift: [0.75 kx, -0.5 ky]
          affect: "x"

    # helpers to draw mcu area
    _helper_mcu_topleft:
      anchor:
        - ref: matrix_inner_top
          shift: [0.5 kx, 0.5 ky]
    _helper_mcu_bottomright:
      anchor:
        - ref: thumbfan_far_thumb
          shift: [0.75 kx, -0.5 ky]
          rotate: -90
    _helper_mcu_bottomleft:
      anchor:
        - ref: _helper_mcu_bottomright
          shift: [-thumb_shift, 0]
    _helper_mcu_topright:
      anchor:
        - ref: _helper_mcu_topleft
          affect: "y"
        - ref: _helper_mcu_bottomright
          affect: "x"
    _helper_mcu_topmiddle:
      anchor:
        - aggregate.parts:
          - ref: _helper_mcu_topleft
          - ref: _helper_mcu_topright

    _helper_mcu_cover_holes_low:
      anchor:
        - ref: _helper_mcu_bottomright
          rotate: 60
        - shift: [0, 3 * 2]
    _helper_mcu_cover_holes_high:
      anchor:
        - ref: _helper_mcu_bottomleft
          rotate: -30
        - shift: [0, 1.73205081 * 2]

    _helper_thumbfan_bottom:
      anchor:
        - ref: thumbfan_far_thumb
          shift: [-0.75 kx, -0.5 ky]
    _helper_thumbfan_bottomleft:
      anchor:
        - ref: thumbfan_near_thumb
          shift: [-0.5 kx, -0.5 ky]

    _helper_matrix_topleft:
      anchor:
        - ref: matrix_pinky_top
          shift: [-0.5 px, 0.5 ky]
    _helper_matrix_bottomleft:
      anchor:
        - ref: matrix_pinky_bottom
          shift: [-0.5 px, -0.5 ky]

    _helper_mcu_center:
      anchor:
        - ref: _helper_mcu_topmiddle
          shift: [0, -0.5 mcu_height]

outlines:
  raw:
    - what: rectangle
      where:
      - -/_helper_.*/
      asym: source
      size: [kx + 2, ky + 2]
      corner: pd
  switches:
    - what: rectangle
      where:
      - -/_helper_.*/
      size: 14
  switches_outer:
    - what: rectangle
      where:
      - -/_helper_.*/
      size: 15

  board_matrix:
    - what: rectangle
      where:
      - /^matrix_.*/
      size: [kx, ky]
      bound: true

  board_thumbfan:
    - what: rectangle
      where:
      - /^thumbfan_.*/
      size: [kx, ky]
      bound: true
    - what: rectangle
      where:
      - thumbfan_far_thumb
      size: [2 kx, ky]
      adjust:
        - shift: [-kx, 0]
    - what: rectangle
      where:
      - thumbfan_near_thumb
      size: [2 kx, 2 ky]
      adjust:
        - shift: [0.5 kx, 1 ky]
    - what: rectangle
      where:
      - matrix_inner_bottom
      size: [kx, 2 ky]
      adjust:
        - shift: [0, -0.5 ky]

  board_mcu:
    - what: polygon
      points:
      - _helper_mcu_bottomleft
      - _helper_mcu_bottomright
      - _helper_mcu_topright
      - _helper_mcu_topleft

  mcu_cover_holes:
  - what: circle
    where:
    - /_helper_mcu_cover_holes_.*/
    radius: screw_hole_size

  keywell_holes:
    - switches
  keywell:
    - board_matrix
    - board_thumbfan
  board:
    - keywell
    - name: board_mcu
      fillet: 1.5
  mcu_cover:
    - name: board_mcu
      expand: -0.5
    - -mcu_cover_holes

  _preview_mcu:
    - what: rectangle
      where:
      - ref: _helper_mcu_center
      size: [mcu_width, mcu_height]
  _preview_keycaps:
    - what: rectangle
      where:
      - - -/_helper_.*/
        - -/thumbfan_far_thumb/
      size: [kx - 0.5, ky - 0.5]
      bound: false
      corner: 1.5
    - what: rectangle
      where:
      - thumbfan_far_thumb
      size: [1.5 kx - 0.5, ky - 0.5]
      corner: 1.5

  _preview_battery:
    - what: rectangle
      where:
      - ref: _helper_mcu_center
      size: [12, 30]

  preview:
    - board
    - -_preview_keycaps
    - -mcu_cover_holes
    - ^mcu_cover
    - ^_preview_mcu
    - ^_preview_battery

pcbs:
  board:
    outlines:
      main:
        outline: board
      keycaps:
        outline: _preview_keycaps
        layer: Dwgs.User
      mcu:
        outline: board_mcu
        layer: Dwgs.User
    footprints:
      choc_hotswap_matrix:
        what: infused-kim/choc
        where:
        - /^matrix_.*/
        params:
          show_keycaps: false
          reverse: true
          hotswap: false
          solder: true
          from: "GND"
          to: "k{{kn}}"
      choc_hotswap_thumbfan:
        what: infused-kim/choc
        where:
        - /^thumbfan_.*/
        params:
          show_keycaps: false
          reverse: true
          hotswap: false
          solder: true
          from: "GND"
          to: "k{{kn}}"
      mcu:
        what: infused-kim/nice_nano_pretty
        where:
          ref:
          - _helper_mcu_center
        params:
          P0: k0
          P1: k1
          P2: k2
          P3: k3
          P4: k4
          P5: k5
          P6: k6
          P7: k7
          P8: k8
          P9: k9
          P10: k10
          P14: k11
          P15: k12
          P16: k13
          P18: k14
          P19: k15
          P20: k16
          P21: k17

          P0_label: k0
          P1_label: k1
          P2_label: k2
          P3_label: k3
          P4_label: k4
          P5_label: k5
          P6_label: k6
          P7_label: k7
          P8_label: k8
          P9_label: k9
          P10_label: k10
          P14_label: k11
          P15_label: k12
          P16_label: k13
          P18_label: k14
          P19_label: k15
          P20_label: k16
          P21_label: k17

      reset:
        what: infused-kim/switch_reset
        where:
          ref:
          - _helper_topright
          shift: [-1.7, -mcu_height - 5.5]
        params:
          reverse: true
          from: RST
          to: GND
      reset_via_rst:
        what: via
        where:
          ref:
          - _helper_topright
          shift: [-2.425, -mcu_height - 5.5]
        params:
          net: "RST"

      power:
        what: infused-kim/switch_power
        where:
          ref:
          - _helper_topright
          shift: [-1.75, -mcu_height - 15]
        params:
          reverse: true
          from: BAT+
          to: RAW
      power_on_r:
        what: infused-kim/text
        where:
          ref:
          - _helper_topright
          shift: [-1.75, -mcu_height - 9.8]
        params:
          reverse: true
          text: "ON"
      power_off_r:
        what: infused-kim/text
        where:
          ref:
          - _helper_topright
          shift: [-1.75, -mcu_height - 20.2]
        params:
          reverse: true
          text: "OFF"

      jstph:
        what: jstph
        where:
          ref:
          - _helper_topright
          shift: [-7.0, -mcu_height - 15]
          rotate: -90
        params:
          neg: "GND"
          pos: "BAT+"
      icon_bat_l:
        what: infused-kim/icon_bat
        where:
          ref:
          - _helper_topright
          shift: [-15, -mcu_height - 15]
          rotate: -90
      icon_bat_r:
        what: infused-kim/icon_bat
        where:
          ref:
          - _helper_topright
          shift: [-15, -mcu_height - 15]
          rotate: 90
        params:
          side: "B"

      mcu_cover_holes:
        what: infused-kim/mounting_hole
        where:
          - /_helper_mcu_cover_holes_.*/
        params:
          outline: 0.5

      jlc_marker:
        what: text
        where:
          - aggregate.parts:
              - ref: matrix_index_bottom
              - ref: thumbfan_near_thumb
            affect: "y"
          - ref: thumbfan_near_thumb
            shift: [0.5 kx, 0]
            affect: "x"
        params:
          text: "JLCJLCJLCJLC"
