units:
  kx: cx
  ky: cy

  pd: 2
  px: kx + pd
  py: ky + pd
points:
  key:
    footprints:
      choc_hotswap:
        type: choc
        params:
          hotswap: true
          reverse: true
          keycaps: true
        nets:
          from: =colrow
          to: =column_net
      diode:
        type: diode
        nets:
          from: =colrow
          to: =row_net
        anchor:
          shift: [0, -5]
  zones:
    matrix:
      anchor:
        shift: [100, -100]
      key:
        padding: ky
        spread: kx
      columns:
        pinky:
          key.column_net: col_pinky
        ring:
          key.stagger: 0.5 ky
          key.column_net: col_ring
        middle:
          key.stagger: 0.3 ky
          key.column_net: col_middle
        index:
          key.stagger: -0.3 ky
          key.column_net: col_index
        inner:
          key.stagger: -0.2 ky
          key.column_net: col_inner
      rows:
        bottom:
          row_net: row_bottom
        home:
          row_net: row_home
        top:
          row_net: row_top
    thumbfan:
      anchor:
        ref: matrix_middle_bottom
        shift: [0.5 kx, -1.5 ky]
      key:
        padding: ky
        spread: kx
      columns:
        near:
          key.column_net: col_middle
        home:
          key:
            splay: -15
            origin: [-0.5 kx, -1 ky]
            column_net: col_index
        far:
          key:
            splay: -15
            origin: [-0.5 kx, -1 ky]
            rotate: 90
            width: 1.5 kx
            shift: [0, 0.25 kx]
            column_net: col_inner
      rows:
        thumb:
          row_net: row_thumb
outlines:
  raw:
    - what: rectangle
      where: true
      asym: source
      size: [kx + 2, ky + 2]
      corner: pd
  keys:
    - what: rectangle
      where: true
      size: [kx - 0.5, ky - 0.5]
      bound: false
  switches:
    - what: rectangle
      where: true
      size: 14
      bound: false
  board_matrix:
    - what: polygon
      points:
        - ref: matrix_pinky_top
          shift: [-0.5 px, 0.5 py]
        - ref: matrix_pinky_top
          shift: [0.5 px-pd, 0.5 py]

        - ref: matrix_ring_top
          shift: [-0.5 px, 0.5 py]
        - ref: matrix_ring_top
          shift: [0.5 px - pd, 0.5 py]

        - ref: matrix_middle_top
          shift: [-0.5 px, 0.5 py]
        - ref: matrix_middle_top
          shift: [0.5 px, 0.5 py]

        - ref: matrix_index_top
          shift: [-0.5 px + pd, 0.5 py]
        - ref: matrix_index_top
          shift: [0.5 px, 0.5 py]

        - ref: matrix_inner_top
          shift: [-0.5 px + pd, 0.5 py]
        - ref: matrix_inner_top
          shift: [0.5 px, 0.5 py]

        - ref: matrix_pinky_bottom
          shift: [4 kx + 0.5 px, -0.5 py]

        - ref: matrix_pinky_bottom
          shift: [-0.5 px, -0.5 py]
  board_thumbfan:
    - what: polygon
      points:
        - ref: matrix_ring_bottom
        - ref: thumbfan_far_thumb
          shift: [0.25 kx + 0.5 px, 2 py]

        - ref: thumbfan_far_thumb
          shift: [0.25 kx + 0.5 px, -0.5 py]
        - ref: thumbfan_far_thumb
          shift: [-0.25 kx - 0.5 px, -0.5 py]

        - ref: thumbfan_home_thumb
          shift: [0.5 px, -0.5 py]

        - ref: thumbfan_near_thumb
          shift: [-0.5 px, -0.5 py]
  _board_mcu_h:
    - what: polygon
      points:
        - ref: matrix_inner_top
          shift: [0.5 kx, 0.5 py]
        - ref: matrix_inner_top
          shift: [3 kx, 0.5 py]
        - ref: matrix_inner_top
          shift: [3 kx, -3 py]
        - ref: matrix_inner_top
          shift: [0.5 kx, -3 py]
  _board_mcu_v:
    - what: polygon
      points:
        - ref: thumbfan_far_thumb
          shift: [0.25 kx + 0.5 px, -0.5 py]
        - ref: thumbfan_far_thumb
          shift: [0.25 kx + 0.5 px + 4 kx, (4/1.732) kx - 0.5 py]
        - ref: thumbfan_far_thumb
          shift: [0.25 kx + 0.5 px + 4 kx, (4/1.732) kx + 2 py]
        - ref: thumbfan_far_thumb
          shift: [0.25 kx + 0.5 px, 2 py]
  board_mcu:
    - name: _board_mcu_h
    - name: _board_mcu_v
      operation: intersect
  board:
    - name: board_matrix
    - name: board_thumbfan
    - name: board_mcu
      operation: add
      fillet: 1
  board_topplate:
    - name: board_matrix
    - name: board_thumbfan
      operation: add
    - name: switches
      operation: subtract
      fillet: 1
  combo:
    - name: board
    - name: keys
      operation: subtract
pcbs:
  board:
    outlines:
      main:
        outline: board
    footprints:
      choc_hotswap:
        what: infused-kim/choc
        where:
        - /matrix_.*/
        - /thumbfan_.*/
        params:
          # keycaps: true
          reverse: true
          hotswap: true
          from: "{{colrow}}"
          to: "{{column_net}}"
      diode:
        what: infused-kim/diode
        where:
        - /matrix_.*/
        - /thumbfan_.*/
        params:
          include_tht: false
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [0, -3.5]
      mcu_left:
        what: promicro
        where:
          ref:
          - matrix_inner_top
          shift: [21.5, -9]
          rotate: 270
        params:
          orientation: down
          P4: row_top
          P5: row_home
          P6: row_bottom
          P7: row_thumb
          P14: col_inner
          P15: col_index
          P18: col_middle
          P19: col_ring
          P20: col_pinky
      reset:
        what: reset_button
        where:
          ref:
          - matrix_inner_top
          shift: [31, -31]
          rotate: 90
        params:
          from: RST
          to: GND
      power:
        what: infused-kim/switch_power
        where:
          ref:
          - matrix_inner_top
          shift: [31, -41]
        params:
          reverse: true
          from: BAT+
      jstph:
        what: jstph
        where:
          ref:
          - matrix_inner_top
          shift: [24, -35]
          rotate: -90
        params:
          neg: "BAT+"
          pos: "GND"
