meta:
  version: 0.1
  name: korne
  author: XuyuanPang

units:
  kx: cx
  ky: cy

  pd: 2
  px: kx + pd
  py: ky + pd

  cpd: 4

  thumb_shift: 1.6 ky

  mcu_width: 17.78
  mcu_height: 33

  pcb_height: 1.6
  bottom_height: 2.5
  bottom_wall_thickness: 1.5
  bottom_wall_adjust: 0.1
  usbc_notch_radius: 3
  usbc_notch_width: 10
  switch_height: 2.2
  plate_height: 1.3
  standoff_height: 3 + 0.2
  socket_height: 2
  magnet_slot_radius: 3.05
  magnet_slot_depth: 2
  rubber_radius: 4.05
  rubber_height: 1.4
  m2r: 1.05 # radius of m2 screw
  screw_hole_size: m2r # screw hole size

points:
  key:
    width: kx
    height: ky
  zones:
    matrix:
      key:
        padding: ky
        spread: u
      columns:
        pinky.key:
          column_net: col_pinky
        ring.key:
          stagger: 0.65 ky
          column_net: col_ring
        middle.key:
          stagger: 0.25 ky
          column_net: col_middle
        index.key:
          stagger: -0.35 ky
          column_net: col_index
        inner.key:
          stagger: -0.2 ky
          column_net: col_inner
      rows:
        bottom:
          row_net: row_bottom
        home:
          row_net: row_home
        top:
          row_net: row_top
    thumbfan:
      anchor:
        - ref: matrix_inner_bottom
          shift: [0.5 kx, -0.5 ky / 1.732]
          rotate: -30
        - shift: [thumb_shift, 0]
          rotate: 90
        - shift: [-0.75 kx, 0.5 ky]
      key:
        spread: -kx
      columns:
        far.key:
          width: 1.5 kx
          column_net: col_inner
        _bridge_far_home.key:
          spread: -0.25 kx - 0.5 (kx - ky)
          splay: -90
          skip: true
        home.key:
          splay: 15
          origin: [0.5 kx, -0.5 ky]
          column_net: col_index
        near.key:
          splay: 15
          origin: [0.5 kx, -0.5 ky]
          column_net: col_middle
      rows:
        thumb.row_net: row_thumb

    _helper_topright:
      anchor:
        - ref: matrix_inner_top
          shift: [0, 0.5 py]
          affect: "y"
        - ref: thumbfan_far_thumb
          shift: [0.75 kx, -0.5 ky]
          affect: "x"

    # helpers to draw mcu area
    _helper_mcu_topleft:
      anchor:
        - ref: matrix_inner_top
          shift: [0.5 kx, 0.5 py]
    _helper_mcu_bottomright:
      anchor:
        - ref: thumbfan_far_thumb
          shift: [0.75 kx, -0.5 ky]
          rotate: -90
    _helper_mcu_bottomleft:
      anchor:
        - ref: _helper_mcu_bottomright
          shift: [-thumb_shift, 0]
    _helper_mcu_topright:
      anchor:
        - ref: _helper_mcu_topleft
          affect: "y"
        - ref: _helper_mcu_bottomright
          affect: "x"
    _helper_mcu_middle:
      anchor:
        - aggregate.parts:
          - ref: _helper_mcu_topleft
          - ref: _helper_mcu_topright

    _helper_mcu_cover_holes_low:
      anchor:
        - ref: _helper_mcu_bottomright
          rotate: 60
        - shift: [0, 3 * 2]
    _helper_mcu_cover_holes_high:
      anchor:
        - ref: _helper_mcu_bottomleft
          rotate: -30
        - shift: [0, 1.73205081 * 2]

    _helper_screw_holes_topleft:
      anchor:
        - aggregate.parts:
          - ref: matrix_pinky_top
          - ref: matrix_ring_top
          affect: "x"
        - aggregate.parts:
          - ref: matrix_pinky_top
          - ref: matrix_pinky_home
          affect: "y"
    _helper_screw_holes_bottomleft:
      anchor:
        - aggregate.parts:
          - ref: matrix_pinky_home
          - ref: matrix_ring_home
          affect: "x"
        - aggregate.parts:
          - ref: matrix_pinky_home
          - ref: matrix_pinky_bottom
          affect: "y"
    _helper_screw_holes_topright:
      anchor:
        - aggregate.parts:
          - ref: matrix_index_top
          - ref: matrix_inner_top
          affect: "x"
        - aggregate.parts:
          - ref: matrix_index_top
          - ref: matrix_index_home
          affect: "y"
    _helper_screw_holes_palm:
      anchor:
        - ref: matrix_middle_bottom
          shift: [-0.3 kx, -1.1 ky]
    _helper_screw_holes_thumb:
      anchor:
        - ref: thumbfan_far_thumb
          shift: [5, 3 + 0.5 kx]

templates:
  board_matrix:
    $params: [_padding]
    what: polygon
    points:
      - ref: matrix_pinky_top
        shift: [-0.5 (kx + _padding), 0.5 (ky + _padding)]

      - - ref: matrix_ring_top
          shift: [-0.5 (kx + _padding), 0]
          affect: "x"
        - ref: matrix_pinky_top
          shift: [0, 0.5 (ky + _padding)]
          affect: "y"

      - ref: matrix_ring_top
        shift: [-0.5 (kx + _padding), 0.5 (ky + _padding)]

      - - ref: matrix_middle_top
          shift: [-0.5 (kx + _padding), 0]
          affect: "x"
        - ref: matrix_ring_top
          shift: [0, 0.5 (ky + _padding)]
          affect: "y"

      - ref: matrix_middle_top
        shift: [-0.5 (kx + _padding), 0.5 (ky + _padding)]
      - ref: matrix_middle_top
        shift: [0.5 (kx + _padding), 0.5 (ky + _padding)]

      - - ref: matrix_middle_top
          shift: [0.5 (kx + _padding), 0]
          affect: "x"
        - ref: matrix_index_top
          shift: [0, 0.5 (ky + _padding)]
          affect: "y"

      - ref: matrix_index_top
        shift: [0.5 (kx + _padding), 0.5 (ky + _padding)]

      - - ref: matrix_index_top
          shift: [0.5 (kx + _padding), 0]
          affect: "x"
        - ref: matrix_inner_top
          shift: [0, 0.5 (ky + _padding)]
          affect: "y"

      - ref: matrix_inner_top
        shift: [0.5 kx, 0.5 (ky + _padding)] # X axis shift 0.5kx to avoid overlap

      - - ref: matrix_inner_bottom
          shift: [0.5 kx, 0]
          affect: "x"
        - ref: matrix_pinky_bottom
          shift: [0, -0.5 (ky + _padding)]
          affect: "y"

      - ref: matrix_pinky_bottom
        shift: [-0.5 (kx + _padding), -0.5 (ky + _padding)]

  board_thumbfan:
    $params: [_padding]
    what: polygon
    points:
      - ref: matrix_pinky_home

      - ref: thumbfan_far_thumb
        shift: [0.75 kx, 2 (ky + _padding)]

      - ref: thumbfan_far_thumb
        shift: [0.75 kx, -0.5 (ky + _padding)]

      - ref: thumbfan_far_thumb
        shift: [-0.25 kx - 0.5 (kx + _padding), -0.5 (ky + _padding)]

      - ref: thumbfan_far_thumb
        shift: [-0.25 kx - 0.5 (kx + _padding), 0.5 (ky + _padding)]

      - ref: thumbfan_near_thumb
        shift: [-0.5 (kx + _padding), -0.5 (ky + _padding)]

  board_mcu:
    $params: [_padding]
    what: polygon
    points:
      - ref: _helper_mcu_bottomleft
      - ref: thumbfan_far_thumb
        shift: [0.75kx, -0.5 (ky + _padding)]
      - - ref: thumbfan_far_thumb
          shift: [0.75kx, -0.5 (ky + _padding)]
          affect: "x"
        - ref: matrix_inner_top
          shift: [0.5 kx, 0.5 (ky + _padding)]
          affect: "y"
      - ref: matrix_inner_top
        shift: [0.5 kx, 0.5 (ky + _padding)]

outlines:
  raw:
    - what: rectangle
      where:
      - -/_helper_.*/
      asym: source
      size: [kx + 2, ky + 2]
      corner: pd
  keys:
    - what: rectangle
      where:
      - -/_helper_.*/
      size: [kx - 0.5, ky - 0.5]
      bound: false
  switches:
    - what: rectangle
      where:
      - -/_helper_.*/
      size: 14
  switches_outer:
    - what: rectangle
      where:
      - -/_helper_.*/
      size: 15
  board_matrix:
    - $extends: templates.board_matrix
      $args: [pd]
  board_thumbfan:
    - $extends: templates.board_thumbfan
      $args: [0]
  board_mcu:
    - what: polygon
      points:
      - _helper_mcu_bottomleft
      - _helper_mcu_bottomright
      - _helper_mcu_topright
      - _helper_mcu_topleft
  screw_holes:
  - what: circle
    where:
    - /_helper_screw_holes_.*/
    radius: screw_hole_size
  mcu_cover_holes:
  - what: circle
    where:
    - /_helper_mcu_cover_holes_.*/
    radius: screw_hole_size
  keywell_holes:
    - switches
    - screw_holes
  keywell:
    - board_matrix
    - board_thumbfan
  board:
    - keywell
    - name: board_mcu
      fillet: 1.5
  topplate_fr4:
    - name: keywell
      fillet: 1.5
    - -keywell_holes
  bottomplate_fr4:
    - board
    - -screw_holes
  mcu_cover:
    - board_mcu
    - -mcu_cover_holes
  combo:
    - board
    - -keys

  # for cases
  _case_matrix:
    - $extends: templates.board_matrix
      $args: [cpd]
  _case_thumbfan:
    - $extends: templates.board_thumbfan
      $args: [cpd]
  _case_mcu:
    - $extends: templates.board_mcu
      $args: [cpd]

  _case_keywell:
    - _case_matrix
    - _case_thumbfan
  _case_board:
    - _case_matrix
    - _case_thumbfan
    - name: _case_mcu
      fillet: 1.5

  _case_top:
    - name: _case_keywell
      fillet: 1.5
    - -keywell_holes

  _case_bottom_inner:
    - name: board
      expand: bottom_wall_adjust
  _case_bottom_outer:
    - name: board
      expand: bottom_wall_thickness + bottom_wall_adjust
  _case_bottom_wall:
    - _case_bottom_outer
    - -_case_bottom_inner

  _case_mountings_outer:
    - what: circle
      where:
      - /_helper_screw_holes_.*/
      radius: 3
  _case_mountings_inner:
    - what: circle
      where:
      - /_helper_screw_holes_.*/
      radius: 1.4

  _case_sw_notch:
    - what: rectangle
      where:
        - ref: _helper_mcu_bottomright
          rotate: 30
        - shift: [0, 17.9]
      size: 18

  _case_magnet_slots:
    - what: circle
      where:
      - ref: matrix_pinky_home
      radius: magnet_slot_radius
    - what: circle
      where:
      - ref: matrix_middle_top
        shift: [0, -0.5 ky]
      radius: magnet_slot_radius
    - what: circle
      where:
      - ref: matrix_index_bottom
        shift: [0, -ky]
      radius: magnet_slot_radius
    - what: circle
      where:
        - ref: matrix_inner_top
          shift: [kx, -0.5 ky]
      radius: magnet_slot_radius
    - what: circle
      where:
        - ref: matrix_inner_bottom
          shift: [kx, -ky]
      radius: magnet_slot_radius

  _case_usbc_notch:
    - what: circle
      where:
        - ref: _helper_mcu_middle
          shift: [-0.5 * usbc_notch_width, 0]
      radius: usbc_notch_radius
    - what: circle
      where:
        - ref: _helper_mcu_middle
          shift: [0.5 * usbc_notch_width, 0]
      radius: usbc_notch_radius
    - what: rectangle
      where:
        - ref: _helper_mcu_middle
      size: [usbc_notch_width, usbc_notch_radius * 2]

  _case_rubbers:
    - what: circle
      radius: rubber_radius
      where:
      - ref: matrix_pinky_top
        shift: [0.6, 0.5 py - rubber_radius - 1]
    - what: circle
      radius: rubber_radius
      where:
      - ref: matrix_pinky_top
        shift: [-0.5 px + rubber_radius + 1, -0.6]

    - what: circle
      radius: rubber_radius
      where:
      - ref: matrix_pinky_bottom
        shift: [0.6, -(0.5 py - rubber_radius - 1)]
    - what: circle
      radius: rubber_radius
      where:
      - ref: matrix_pinky_bottom
        shift: [-0.5 px + rubber_radius + 1, 0.6]

    - what: circle
      radius: rubber_radius
      where:
      - ref: _helper_topright
        shift: [-2 * rubber_radius - 2, -rubber_radius - 0.6]
    - what: circle
      radius: rubber_radius
      where:
      - ref: _helper_topright
        shift: [-rubber_radius - 0.6, -2 * rubber_radius - 2]

    - what: circle
      radius: rubber_radius
      where:
      - ref: thumbfan_far_thumb
        shift: [-0.75 kx, -0.5 ky]
        rotate: -60
      - shift: [1.5, 2.5 rubber_radius + 0.7 ]

    - what: circle
      radius: rubber_radius
      where:
      - ref: thumbfan_far_thumb
        shift: [-0.75 kx, -0.5 ky]
        rotate: -60
      - shift: [-5.8, 2.5 rubber_radius - 2]

    - what: circle
      radius: rubber_radius
      where:
      - ref: matrix_middle_top
        shift: [-rubber_radius, rubber_radius]
    - what: circle
      radius: rubber_radius
      where:
      - ref: matrix_middle_top
        shift: [rubber_radius, rubber_radius]

cases:
  top:
    - name: topplate_fr4
      extrude: switch_height
    - name: switches_outer
      extrude: switch_height - plate_height
      operation: subtract

  _standoffs:
    - name: _case_mountings_outer
      extrude: bottom_height + socket_height
    - name: _case_mountings_inner
      shift: [0, 0, bottom_height + socket_height - standoff_height]
      extrude: standoff_height
      operation: subtract
  _standoffs_inner:
    - name: _case_mountings_inner
      extrude: bottom_height
  _magnet_slots:
    - name: _case_magnet_slots
      extrude: magnet_slot_depth
      shift: [0, 0, bottom_height - magnet_slot_depth]
  _rubbers:
    - name: _case_rubbers
      extrude: rubber_height

  _bottom_base:
    - name: _case_bottom_outer
      extrude: bottom_height
  _bottom_wall:
    - name: _case_bottom_wall
      extrude: bottom_height + socket_height + pcb_height + switch_height

  _sw_notch:
    - name: _case_sw_notch
      extrude: 10
      shift: [0, 0, bottom_height + socket_height + pcb_height]
      rotate: [0,45, 0]

  _usbc_notch:
    - name: _case_usbc_notch
      extrude: 5
      rotate: [-90, 0, 0]
      shift: [0, 0, bottom_height + socket_height + pcb_height + 3]

  bottom:
    - _bottom_base
    - _bottom_wall
    - -_standoffs_inner
    - _standoffs
    - -_magnet_slots
    - -_rubbers
    - -_sw_notch
    - -_usbc_notch

  # for debugging
  pcb:
    - name: board
      extrude: pcb_height

pcbs:
  board_topplate:
    outlines:
      main:
        outline: topplate_fr4
  board_bottomplate:
    outlines:
      main:
        outline: bottomplate_fr4
  board:
    outlines:
      main:
        outline: board
      # mcu:
      #   outline: board_mcu
      #   layer: F.SilkS
      # notch:
      #   outline: _case_sw_notch
      #   layer: F.SilkS
    footprints:
      choc_hotswap_matrix:
        what: infused-kim/choc
        where:
        - /matrix_.*/
        params:
          reverse: true
          hotswap: true
          from: "{{colrow}}"
          to: "{{column_net}}"
      choc_hotswap_thumb:
        what: infused-kim/choc
        where:
        - /thumbfan_home_thumb/
        - /thumbfan_near_thumb/
        params:
          reverse: true
          hotswap: true
          from: "{{colrow}}"
          to: "{{column_net}}"
      choc_hotswap_thumb_far:
        what: infused-kim/choc
        where:
        - /thumbfan_far_thumb/
        params:
          reverse: true
          hotswap: true
          from: "{{colrow}}"
          to: "{{column_net}}"
          keycaps_x: 1.5 kx
      diode:
        what: diode
        where:
        - -/_helper_.*/
        params:
          include_tht: true
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [1, -5]
          rotate: 180
      key_vias:
        what: via
        where:
        - /matrix_ring_.*/
        - /matrix_middle_.*/
        - /matrix_index_.*/
        - /matrix_inner_.*/
        - matrix_pinky_top
        - /thumbfan_.*/
        adjust:
          shift: [0, 8.5]
        params:
          net: "{{column_net}}"
      mcu:
        what: infused-kim/nice_nano_pretty
        where:
          ref:
          - _helper_mcu_middle
          shift: [0, -0.5 mcu_height]
        params:
          P4: row_top
          P5: row_home
          P6: row_bottom
          P7: row_thumb
          P14: col_inner
          P15: col_index
          P18: col_middle
          P19: col_ring
          P20: col_pinky
          # nice!view
          P1: CS
          P2: MOSI
          P3: SCK

          P20_label: 'C0'
          P19_label: 'C1'
          P18_label: 'C2'
          P15_label: 'C3'
          P14_label: 'C4'

          P1_label: 'CS'
          P2_label: 'SDA'
          P3_label: 'SCL'
          P4_label: 'R0'
          P5_label: 'R1'
          P6_label: 'R2'
          P7_label: 'R3'

      niceview:
        what: infused-kim/nice_view
        where:
          ref:
          - _helper_mcu_middle
          shift: [0, -0.5 mcu_height - 4]
        params:
          reverse: true
          jumpers_at_bottom: true

      reset:
        what: infused-kim/switch_reset
        where:
          ref:
          - _helper_topright
          shift: [-1.7, -mcu_height - 5.5]

        params:
          reverse: true
      reset_via_gnd:
        what: via
        where:
          ref:
          - _helper_topright
          shift: [-2.425, -mcu_height - 5.5]
        params:
          net: "GND"
      reset_via_rst:
        what: via
        where:
          ref:
          - _helper_topright
          shift: [-0.975, -mcu_height - 5.5]
        params:
          net: "RST"

      power:
        what: infused-kim/switch_power
        where:
          ref:
          - _helper_topright
          shift: [-1.75, -mcu_height - 15]
        params:
          reverse: true
          from: BAT+
          to: RAW
      power_on_r:
        what: infused-kim/text
        where:
          ref:
          - _helper_topright
          shift: [-1.75, -mcu_height - 9.5]
        params:
          reverse: true
          text: "ON"
      power_off_r:
        what: infused-kim/text
        where:
          ref:
          - _helper_topright
          shift: [-1.75, -mcu_height - 20.5]
        params:
          reverse: true
          text: "OFF"

      jstph:
        what: jstph
        where:
          ref:
          - _helper_topright
          shift: [-7.0, -mcu_height - 15]
          rotate: -90
        params:
          neg: "GND"
          pos: "BAT+"
      icon_bat_l:
        what: infused-kim/icon_bat
        where:
          ref:
          - _helper_topright
          shift: [-15, -mcu_height - 15]
          rotate: -90
      icon_bat_r:
        what: infused-kim/icon_bat
        where:
          ref:
          - _helper_topright
          shift: [-15, -mcu_height - 15]
          rotate: 90
        params:
          side: "B"

      mounting_holes:
        what: infused-kim/mounting_hole
        where:
          - /_helper_screw_holes_.*/
        params:
          outline: 0.5
      mcu_cover_holes:
        what: infused-kim/mounting_hole
        where:
          - /_helper_mcu_cover_holes_.*/
        params:
          outline: 0.5

      info_l:
        what: text
        where:
          ref:
          - matrix_pinky_bottom
          shift: [0.6 kx, -2]
        params:
          text: "korne v0.1\\nby Xuyuan Pang"
          justify: left
      info_r:
        what: text
        where:
          ref:
            - matrix_pinky_bottom
          shift: [0.6 kx, -2]
        params:
          layer: B.SilkS
          text: "korne v0.1\\nby Xuyuan Pang"
          justify: right mirror

      jlc_marker:
        what: text
        where:
          - aggregate.parts:
              - ref: matrix_index_bottom
              - ref: thumbfan_near_thumb
            affect: "y"
          - ref: thumbfan_near_thumb
            shift: [0.5 kx, 0]
            affect: "x"
        params:
          text: "JLCJLCJLCJLC"
