units:
  kx: cx
  ky: cy

  pd: 2
  px: kx + pd
  py: ky + pd

  mcu_width: 17.78
  mcu_height: 33

points:
  zones:
    matrix:
      anchor:
        shift: [100, -100]
      key:
        padding: ky
        spread: kx
      columns:
        pinky:
          key.column_net: col_pinky
        ring:
          key.stagger: 0.6 ky
          key.column_net: col_ring
        middle:
          key.stagger: 0.25 ky
          key.column_net: col_middle
        index:
          key.stagger: -0.3 ky
          key.column_net: col_index
        inner:
          key.stagger: -0.2 ky
          key.column_net: col_inner
      rows:
        bottom:
          row_net: row_bottom
        home:
          row_net: row_home
        top:
          row_net: row_top
    thumbfan:
      anchor:
        ref: matrix_middle_bottom
        shift: [0.5 kx, -1.5 ky]
      key:
        padding: ky
        spread: kx
      columns:
        near:
          key.column_net: col_middle
        home:
          key:
            splay: -15
            origin: [-0.5 kx, -1 ky]
            column_net: col_index
        far:
          key:
            splay: -15
            origin: [-0.5 kx, -1 ky]
            rotate: 90
            width: 1.5 kx
            shift: [0, 0.25 kx]
            column_net: col_inner
      rows:
        thumb:
          row_net: row_thumb
    _helper_topright:
      anchor:
        - ref: matrix_inner_top
          shift: [0.5 px, 0.5 py]
          affect: "y"
        - ref: thumbfan_far_thumb
          shift: [0.25 kx + 0.5 px, -0.5 py]
          affect: "x"
    _helper_mcu_middle:
      anchor:
        - aggregate.parts:
          - ref: matrix_inner_top
            shift: [0.5 px, 0.5 py]
          - ref: _helper_topright
    _helper_screw_holes_topleft:
      anchor:
        - ref: matrix_pinky_top
          shift: [0.5 kx, -0.5 ky]
    _helper_screw_holes_bottomleft:
      anchor:
        - ref: matrix_pinky_bottom
          shift: [0.5 kx, 0.5 ky]
    _helper_screw_holes_topright:
      anchor:
        - ref: matrix_index_top
          shift: [0.5 kx, -0.5 ky]
    _helper_screw_holes_palm:
      anchor:
        - ref: matrix_middle_bottom
          shift: [-0.3 kx, -1.1 ky]
    _helper_screw_holes_thumb:
      anchor:
        - ref: thumbfan_far_thumb
          shift: [0, 0.5 py + 2]

outlines:
  raw:
    - what: rectangle
      where:
      - -/_helper_.*/
      asym: source
      size: [kx + 2, ky + 2]
      corner: pd
  keys:
    - what: rectangle
      where:
      - -/_helper_.*/
      size: [kx - 0.5, ky - 0.5]
      bound: false
  switches:
    - what: rectangle
      where:
      - -/_helper_.*/
      size: 14
      bound: false
  board_matrix:
    - what: polygon
      points:
        - ref: matrix_pinky_top
          shift: [-0.5 px, 0.5 py]
        - ref: matrix_pinky_top
          shift: [0.5 px-pd, 0.5 py]

        - ref: matrix_ring_top
          shift: [-0.5 px, 0.5 py]
        - ref: matrix_ring_top
          shift: [0.5 px - pd, 0.5 py]

        - ref: matrix_middle_top
          shift: [-0.5 px, 0.5 py]
        - ref: matrix_middle_top
          shift: [0.5 px, 0.5 py]

        - ref: matrix_index_top
          shift: [-0.5 px + pd, 0.5 py]
        - ref: matrix_index_top
          shift: [0.5 px, 0.5 py]

        - ref: matrix_inner_top
          shift: [-0.5 px + pd, 0.5 py]
        - ref: matrix_inner_top
          shift: [0.5 px, 0.5 py]

        - ref: matrix_pinky_bottom
          shift: [4 kx + 0.5 px, -0.5 py]

        - ref: matrix_pinky_bottom
          shift: [-0.5 px, -0.5 py]
  board_thumbfan:
    - what: polygon
      points:
        - ref: matrix_ring_bottom
        - ref: thumbfan_far_thumb
          shift: [0.25 kx + 0.5 px, 2 py]

        - ref: thumbfan_far_thumb
          shift: [0.25 kx + 0.5 px, -0.5 py]
        - ref: thumbfan_far_thumb
          shift: [-0.25 kx - 0.5 px, -0.5 py]

        - ref: thumbfan_home_thumb
          shift: [0.5 px, -0.5 py]

        - ref: thumbfan_near_thumb
          shift: [-0.5 px, -0.5 py]
  _board_mcu_h:
    - what: polygon
      points:
        - ref: matrix_inner_top
          shift: [0.5 kx, 0.5 py]
        - ref: _helper_topright
        - ref: _helper_topright
          shift: [0, -3.5 py]
        - ref: matrix_inner_top
          shift: [0.5 kx, -3 py]
  _board_mcu_v:
    - what: polygon
      points:
        - ref: thumbfan_far_thumb
          shift: [0.25 kx + 0.5 px, -0.5 py]
        - ref: _helper_topright
        - ref: _helper_topright
          shift: [-3 kx, 0]
        - ref: thumbfan_far_thumb
          shift: [0.25 kx + 0.5 px, 3 py]
  board_mcu:
    - name: _board_mcu_h
    - name: _board_mcu_v
      operation: intersect
  screw_holes:
  - what: circle
    where:
    - /_helper_screw_holes_.*/
    radius: 1.05
    bound: false
  all_holes:
    - switches
    - screw_holes
  keywell:
    - board_matrix
    - board_thumbfan
  board:
    - keywell
    - name: board_mcu
      fillet: 1
  topplate:
    - name: keywell
      fillet: 1
    - -all_holes
  bottomplate:
    - board
    - -screw_holes
  combo:
    - board
    - -keys

pcbs:
  board:
    outlines:
      main:
        outline: board
    footprints:
      choc_hotswap_matrix:
        what: infused-kim/choc
        where:
        - /matrix_.*/
        params:
          reverse: true
          hotswap: true
          from: "{{colrow}}"
          to: "{{column_net}}"
      choc_hotswap_thumb:
        what: infused-kim/choc
        where:
        - /thumbfan_home_thumb/
        - /thumbfan_near_thumb/
        params:
          reverse: true
          hotswap: true
          from: "{{colrow}}"
          to: "{{column_net}}"
      choc_hotswap_thumb_far:
        what: infused-kim/choc
        where:
        - /thumbfan_far_thumb/
        params:
          reverse: true
          hotswap: true
          from: "{{colrow}}"
          to: "{{column_net}}"
          keycaps_x: 1.5 kx
      diode:
        what: infused-kim/diode
        where:
        - -/helper.*/
        params:
          include_tht: true
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [1, -7]
          rotate: 180
      mcu:
        what: infused-kim/nice_nano_pretty
        where:
          ref:
          - _helper_mcu_middle
          shift: [0, -0.5 mcu_height]
        params:
          P4: row_top
          P5: row_home
          P6: row_bottom
          P7: row_thumb
          P14: col_inner
          P15: col_index
          P18: col_middle
          P19: col_ring
          P20: col_pinky
          # nice!view
          P1: CS
          P2: MOSI
          P3: SCK

          RAW_label: 'RAW'
          GND_label: 'GND'
          RST_label: 'RST'
          VCC_label: 'VCC'
          P21_label: 'P21'
          P20_label: 'P20'
          P19_label: 'P19'
          P18_label: 'P18'
          P15_label: 'P15'
          P14_label: 'P14'
          P16_label: 'P16'
          P10_label: 'P10'

          P1_label: 'P1'
          P0_label: 'P0'
          P2_label: 'P2'
          P3_label: 'P3'
          P4_label: 'P4'
          P5_label: 'P5'
          P6_label: 'P6'
          P7_label: 'P7'
          P8_label: 'P8'
          P9_label: 'P9'

      niceview:
        what: infused-kim/nice_view
        where:
          ref:
          - _helper_mcu_middle
          shift: [0, -0.5 mcu_height - 3]
        params:
          reverse: true
          jumpers_at_bottom: true
      reset:
        what: infused-kim/switch_reset
        where:
          ref:
          - _helper_topright
          shift: [-1.5, -mcu_height - 4]
        params:
          reverse: true
      power:
        what: infused-kim/switch_power
        where:
          ref:
          - _helper_topright
          shift: [-1.75, -mcu_height - 13]
        params:
          reverse: true
          from: BAT+
          to: RAW
      jstph:
        what: jstph
        where:
          ref:
          - matrix_inner_top
          shift: [24, -35.5]
          rotate: -90
        params:
          neg: "GND"
          pos: "BAT+"
      mounting_holes:
        what: infused-kim/mounting_hole
        where:
          - /_helper_screw_holes_.*/
        params:
          outline: 0.5
      info_l:
        what: text
        where:
          ref:
          - matrix_pinky_bottom
          shift: [0.6 kx, -2]
        params:
          text: "mycorne\\nby Xuyuan Pang"
          justify: left
      info_r:
        what: text
        where:
          ref:
            - matrix_pinky_bottom
          shift: [0.6 kx, -2]
        params:
          layer: B.SilkS
          text: "mycorne\\nby Xuyuan Pang"
          justify: right mirror
