meta:
  version: 0.1
  name: korne
  author: XuyuanPang

units:
  kx: u # MX-spaced columns
  ky: cy # choc-spaced rows

  pd: 2
  px: kx + pd
  py: ky + pd

  cpd: 4

  mcu_width: 17.78
  mcu_height: 33

  pcb_height: 1.6
  bottom_height: 2
  standoff_height: 3
  socket_height: 2
  magnet_slot_radius: 3
  magnet_slot_depth: 1.5
  rubber_radius: 4
  rubber_height: 1.25
  m2r: 1.05 # radius of m2 screw
  screw_hole_size: m2r # screw hole size

points:
  zones:
    matrix:
      key:
        padding: ky
        spread: kx
      columns:
        pinky:
          key.column_net: col_pinky
        ring:
          key.stagger: 0.65 ky
          key.column_net: col_ring
        middle:
          key.stagger: 0.25 ky
          key.column_net: col_middle
        index:
          key.stagger: -0.35 ky
          key.column_net: col_index
        inner:
          key.stagger: -0.2 ky
          key.column_net: col_inner
      rows:
        bottom:
          row_net: row_bottom
        home:
          row_net: row_home
        top:
          row_net: row_top
    thumbfan:
      anchor:
        ref: matrix_middle_bottom
        shift: [0.5 kx, -1.6 ky]
      key:
        padding: ky
        spread: kx
      columns:
        near:
          key.column_net: col_middle
        home:
          key:
            splay: -15
            origin: [-0.5 kx, -1 ky]
            column_net: col_index
        far:
          key:
            splay: -15
            origin: [-0.5 kx, -1 ky]
            rotate: 90
            width: 1.5 kx
            shift: [0, 0.25 kx]
            column_net: col_inner
      rows:
        thumb:
          row_net: row_thumb

    _helper_topright:
      anchor:
        - ref: matrix_inner_top
          shift: [0, 0.5 py]
          affect: "y"
        - ref: thumbfan_far_thumb
          shift: [0.75 kx, -0.5 py]
          affect: "x"
    _helper_mcu_middle:
      anchor:
        - aggregate.parts:
          - ref: matrix_inner_top
            shift: [0.5 kx, 0.5 py]
          - ref: _helper_topright
    _helper_screw_holes_topleft:
      anchor:
        - ref: matrix_pinky_top
          shift: [0.5 kx, -0.5 ky]
    _helper_screw_holes_bottomleft:
      anchor:
        - ref: matrix_pinky_bottom
          shift: [0.5 kx, 0.5 ky]
    _helper_screw_holes_topright:
      anchor:
        - ref: matrix_index_top
          shift: [0.5 kx, -0.5 ky]
    _helper_screw_holes_palm:
      anchor:
        - ref: matrix_middle_bottom
          shift: [-0.3 kx, -1.1 ky]
    _helper_screw_holes_thumb:
      anchor:
        - ref: thumbfan_far_thumb
          shift: [0, 0.5 py + 2]
    _helper_mcu_cover_holes_low:
      anchor:
        - ref: thumbfan_far_thumb
          shift: [0.25 kx + 0.5 * px + 3, -0.18 ky]
    _helper_mcu_cover_holes_high:
      anchor:
        - ref: _helper_mcu_cover_holes_low
          shift: [0, 1.05 py]

templates:
  board_matrix:
    $params: [_padding]
    what: polygon
    points:
      - ref: matrix_pinky_top
        shift: [-0.5 (kx + _padding), 0.5 (ky + _padding)]

      - - ref: matrix_ring_top
          shift: [-0.5 (kx + _padding), 0]
          affect: "x"
        - ref: matrix_pinky_top
          shift: [0, 0.5 (ky + _padding)]
          affect: "y"

      - ref: matrix_ring_top
        shift: [-0.5 (kx + _padding), 0.5 (ky + _padding)]

      - - ref: matrix_middle_top
          shift: [-0.5 (kx + _padding), 0]
          affect: "x"
        - ref: matrix_ring_top
          shift: [0, 0.5 (ky + _padding)]
          affect: "y"

      - ref: matrix_middle_top
        shift: [-0.5 (kx + _padding), 0.5 (ky + _padding)]
      - ref: matrix_middle_top
        shift: [0.5 (kx + _padding), 0.5 (ky + _padding)]

      - - ref: matrix_middle_top
          shift: [0.5 (kx + _padding), 0]
          affect: "x"
        - ref: matrix_index_top
          shift: [0, 0.5 (ky + _padding)]
          affect: "y"

      - ref: matrix_index_top
        shift: [0.5 (kx + _padding), 0.5 (ky + _padding)]

      - - ref: matrix_index_top
          shift: [0.5 (kx + _padding), 0]
          affect: "x"
        - ref: matrix_inner_top
          shift: [0, 0.5 (ky + _padding)]
          affect: "y"

      - ref: matrix_inner_top
        shift: [0.5 kx, 0.5 (ky + _padding)] # X axis shift 0.5kx to avoid overlap

      - ref: matrix_pinky_bottom
        shift: [4.5 kx, -0.5 (ky + _padding)]

      - ref: matrix_pinky_bottom
        shift: [-0.5 (kx + _padding), -0.5 (ky + _padding)]

  board_thumbfan:
    $params: [_padding]
    what: polygon
    points:
      - ref: matrix_ring_bottom

      - ref: thumbfan_far_thumb
        shift: [0.75 kx, 2 (ky + _padding)]

      - ref: thumbfan_far_thumb
        shift: [0.75 kx, -0.5 (ky + _padding)]

      - ref: thumbfan_far_thumb
        shift: [-0.25 kx - 0.5 (kx + _padding), -0.5 (ky + _padding)]

      - ref: thumbfan_far_thumb
        shift: [-0.25 kx - 0.5 (kx + _padding), 0.5 (ky + _padding)]

      - ref: thumbfan_near_thumb
        shift: [-0.5 (kx + _padding), -0.5 (ky + _padding)]

  _board_mcu_v:
    $params: [_padding]
    what: polygon
    points:
      - ref: matrix_inner_top
        shift: [0.5 kx, 0.5 (ky + _padding)]
      - ref: _helper_topright
        shift: [0.5 * (_padding - pd), 0.5 * (_padding - pd)]
      - ref: _helper_topright
        shift: [0.5 * (_padding - pd), 0.5 * (_padding - pd) - 5 * (ky + _padding)]
      - ref: matrix_inner_top
        shift: [0.5 kx, -5 (ky + _padding)]

  _board_mcu_h:
    $params: [_padding]
    what: polygon
    points:
      - ref: thumbfan_far_thumb
        shift: [0.75 kx, -0.5 (ky + _padding)]
      - ref: _helper_topright
        shift: [0.5 * (_padding - pd), 0.5 * (_padding - pd)]
      - ref: _helper_topright
        shift: [0.5 * (_padding - pd) -3 kx, 0.5 * (_padding - pd)]
      - ref: thumbfan_far_thumb
        shift: [0.75 kx, 3 (ky + _padding)]

outlines:
  raw:
    - what: rectangle
      where:
      - -/_helper_.*/
      asym: source
      size: [kx + 2, ky + 2]
      corner: pd
  keys:
    - what: rectangle
      where:
      - -/_helper_.*/
      size: [kx - 0.5, ky - 0.5]
      bound: false
  switches:
    - what: rectangle
      where:
      - -/_helper_.*/
      size: 14
  switches_outer:
    - what: rectangle
      where:
      - -/_helper_.*/
      size: 15
  board_matrix:
    - $extends: templates.board_matrix
      $args: [pd]
  board_thumbfan:
    - $extends: templates.board_thumbfan
      $args: [pd]
  board_mcu:
    - $extends: templates._board_mcu_v
      $args: [pd]
    - $extends: templates._board_mcu_h
      $args: [pd]
      operation: intersect
  screw_holes:
  - what: circle
    where:
    - /_helper_screw_holes_.*/
    radius: screw_hole_size
  mcu_cover_holes:
  - what: circle
    where:
    - /_helper_mcu_cover_holes_.*/
    radius: screw_hole_size
  keywell_holes:
    - switches
    - screw_holes
  keywell:
    - board_matrix
    - board_thumbfan
  board:
    - keywell
    - name: board_mcu
      fillet: 1.5
  topplate_fr4:
    - name: keywell
      fillet: 1.5
    - -keywell_holes
  bottomplate_fr4:
    - board
    - -screw_holes
  mcu_cover:
    - board_mcu
    - -mcu_cover_holes
  combo:
    - board
    - -keys

  # for cases
  _case_matrix:
    - $extends: templates.board_matrix
      $args: [cpd]
  _case_thumbfan:
    - $extends: templates.board_thumbfan
      $args: [cpd]
  _case_mcu:
    - $extends: templates._board_mcu_v
      $args: [cpd]
    - $extends: templates._board_mcu_h
      $args: [cpd]
      operation: intersect

  _case_keywell:
    - _case_matrix
    - _case_thumbfan
  _case_board:
    - _case_matrix
    - _case_thumbfan
    - name: _case_mcu
      fillet: 1.5
  _case_top:
    - name: _case_keywell
      fillet: 1.5
    - -keywell_holes

  _case_mountings_outer:
    - what: circle
      where:
      - /_helper_screw_holes_.*/
      radius: 2.3
  _case_mountings_inner:
    - what: circle
      where:
      - /_helper_screw_holes_.*/
      radius: 1.35
  _case_magnet_slots:
    - what: circle
      where:
      - ref: matrix_pinky_home
      radius: magnet_slot_radius
    - what: circle
      where:
      - ref: matrix_middle_top
        shift: [0, -0.5 ky]
      radius: magnet_slot_radius
    - what: circle
      where:
      - ref: matrix_index_bottom
        shift: [0, -ky]
      radius: magnet_slot_radius
    - what: circle
      where:
        - ref: matrix_inner_top
          shift: [kx, -0.5 ky]
      radius: magnet_slot_radius
    - what: circle
      where:
        - ref: matrix_inner_bottom
          shift: [kx, -ky]
      radius: magnet_slot_radius

  _case_rubbers:
    - what: circle
      radius: rubber_radius
      where:
      - ref: matrix_pinky_top
        shift: [0.6, 0.5 py - rubber_radius - 1]
    - what: circle
      radius: rubber_radius
      where:
      - ref: matrix_pinky_top
        shift: [-0.5 px + rubber_radius + 1, -0.6]

    - what: circle
      radius: rubber_radius
      where:
      - ref: matrix_pinky_bottom
        shift: [0.6, -(0.5 py - rubber_radius - 1)]
    - what: circle
      radius: rubber_radius
      where:
      - ref: matrix_pinky_bottom
        shift: [-0.5 px + rubber_radius + 1, 0.6]

    - what: circle
      radius: rubber_radius
      where:
      - ref: _helper_topright
        shift: [-2 * rubber_radius - 2, -rubber_radius - 0.6]
    - what: circle
      radius: rubber_radius
      where:
      - ref: _helper_topright
        shift: [-rubber_radius - 0.6, -2 * rubber_radius - 2]

    - what: circle
      radius: rubber_radius
      where:
      - ref: thumbfan_far_thumb
        shift: [-0.75 kx, -0.5 ky]
        rotate: -60
      - shift: [1.5, 2.5 rubber_radius + 0.7 ]

    - what: circle
      radius: rubber_radius
      where:
      - ref: thumbfan_far_thumb
        shift: [-0.75 kx, -0.5 ky]
        rotate: -60
      - shift: [-5.8, 2.5 rubber_radius - 2]

    - what: circle
      radius: rubber_radius
      where:
      - ref: matrix_middle_top
        shift: [-rubber_radius, rubber_radius]
    - what: circle
      radius: rubber_radius
      where:
      - ref: matrix_middle_top
        shift: [rubber_radius, rubber_radius]

cases:
  top:
    - name: _case_top
      extrude: 3
    - name: board
      extrude: 0.5 * pcb_height
      operation: subtract
    - name: switches_outer
      extrude: 0.8 + 0.9
      operation: subtract

  _bottom_base:
    - name: _case_board
      extrude: bottom_height
  _bottom_wall:
    - name: _case_board
      extrude: bottom_height + socket_height + 0.5 * pcb_height
    - name: board
      extrude: bottom_height + socket_height + 0.5 * pcb_height
      operation: subtract
  _standoffs:
    - name: _case_mountings_outer
      extrude: bottom_height + socket_height
    - name: _case_mountings_inner
      shift: [0, 0, bottom_height + socket_height - standoff_height]
      extrude: standoff_height
      operation: subtract
  _standoffs_inner:
    - name: _case_mountings_inner
      extrude: bottom_height
  _magnet_slots:
    - name: _case_magnet_slots
      extrude: magnet_slot_depth
      shift: [0, 0, 0.85]
  _rubbers:
    - name: _case_rubbers
      extrude: rubber_height
  bottom:
    - _bottom_base
    - _bottom_wall
    - -_standoffs_inner
    - _standoffs
    - -_magnet_slots
    - -_rubbers

pcbs:
  board_topplate:
    outlines:
      main:
        outline: topplate_fr4
  board_bottomplate:
    outlines:
      main:
        outline: bottomplate_fr4
  board:
    outlines:
      main:
        outline: board
    footprints:
      choc_hotswap_matrix:
        what: infused-kim/choc
        where:
        - /matrix_.*/
        params:
          reverse: true
          hotswap: true
          from: "{{colrow}}"
          to: "{{column_net}}"
      choc_hotswap_thumb:
        what: infused-kim/choc
        where:
        - /thumbfan_home_thumb/
        - /thumbfan_near_thumb/
        params:
          reverse: true
          hotswap: true
          from: "{{colrow}}"
          to: "{{column_net}}"
      choc_hotswap_thumb_far:
        what: infused-kim/choc
        where:
        - /thumbfan_far_thumb/
        params:
          reverse: true
          hotswap: true
          from: "{{colrow}}"
          to: "{{column_net}}"
          keycaps_x: 1.5 kx
      diode:
        what: infused-kim/diode
        where:
        - -/_helper_.*/
        params:
          include_tht: true
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [1, -5]
          rotate: 180
      key_vias:
        what: via
        where:
        - /matrix_ring_.*/
        - /matrix_middle_.*/
        - /matrix_index_.*/
        - /matrix_inner_.*/
        - matrix_pinky_top
        - /thumbfan_.*/
        adjust:
          shift: [0, 8.5]
        params:
          net: "{{column_net}}"
      mcu:
        what: infused-kim/nice_nano_pretty
        where:
          ref:
          - _helper_mcu_middle
          shift: [0, -0.5 mcu_height]
        params:
          P4: row_top
          P5: row_home
          P6: row_bottom
          P7: row_thumb
          P14: col_inner
          P15: col_index
          P18: col_middle
          P19: col_ring
          P20: col_pinky
          # nice!view
          P1: CS
          P2: MOSI
          P3: SCK

          RAW_label: 'RAW'
          GND_label: 'GND'
          RST_label: 'RST'
          VCC_label: 'VCC'
          P21_label: 'P21'
          P20_label: 'P20'
          P19_label: 'P19'
          P18_label: 'P18'
          P15_label: 'P15'
          P14_label: 'P14'
          P16_label: 'P16'
          P10_label: 'P10'

          P1_label: 'P1'
          P0_label: 'P0'
          P2_label: 'P2'
          P3_label: 'P3'
          P4_label: 'P4'
          P5_label: 'P5'
          P6_label: 'P6'
          P7_label: 'P7'
          P8_label: 'P8'
          P9_label: 'P9'

      niceview:
        what: infused-kim/nice_view
        where:
          ref:
          - _helper_mcu_middle
          shift: [0, -0.5 mcu_height - 4]
        params:
          reverse: true
          jumpers_at_bottom: true

      reset:
        what: infused-kim/switch_reset
        where:
          ref:
          - _helper_topright
          shift: [-1.8, -mcu_height - 4.5]

        params:
          reverse: true
      reset_via_gnd:
        what: via
        where:
          ref:
          - _helper_topright
          shift: [-2.525, -mcu_height - 4.5]
        params:
          net: "GND"
      reset_via_rst:
        what: via
        where:
          ref:
          - _helper_topright
          shift: [-1.075, -mcu_height - 4.5]
        params:
          net: "RST"

      power:
        what: infused-kim/switch_power
        where:
          ref:
          - _helper_topright
          shift: [-1.75, -mcu_height - 13]
        params:
          reverse: true
          from: BAT+
          to: RAW

      jstph:
        what: jstph
        where:
          ref:
          - _helper_topright
          shift: [-7.5, -mcu_height - 13.6]
          rotate: -90
        params:
          neg: "GND"
          pos: "BAT+"
      icon_bat_l:
        what: infused-kim/icon_bat
        where:
          ref:
          - _helper_topright
          shift: [-15, -mcu_height - 13.6]
          rotate: -90
      icon_bat_r:
        what: infused-kim/icon_bat
        where:
          ref:
          - _helper_topright
          shift: [-15, -mcu_height - 13.6]
          rotate: 90
        params:
          side: "B"

      mounting_holes:
        what: infused-kim/mounting_hole
        where:
          - /_helper_screw_holes_.*/
        params:
          outline: 0.5
      mcu_cover_holes:
        what: infused-kim/mounting_hole
        where:
          - /_helper_mcu_cover_holes_.*/
        params:
          outline: 0.5

      info_l:
        what: text
        where:
          ref:
          - matrix_pinky_bottom
          shift: [0.6 kx, -2]
        params:
          text: "korne v0.1\\nby Xuyuan Pang"
          justify: left
      info_r:
        what: text
        where:
          ref:
            - matrix_pinky_bottom
          shift: [0.6 kx, -2]
        params:
          layer: B.SilkS
          text: "korne v0.1\\nby Xuyuan Pang"
          justify: right mirror
